import { Octokit } from 'octokit';
import { GitHubIssue } from './state';
import { ChatGoogleGenerativeAI } from '@langchain/google-genai';
import { PromptTemplate } from '@langchain/core/prompts';

/**
 * tool: scanBounties
 * Connects to GitHub manually looking for issues with bounties.
 */
export async function scanBounties(token: string, threshold: number): Promise<GitHubIssue[]> {
  const octokit = new Octokit({ auth: token });
  
  try {
    const { data } = await octokit.rest.search.issuesAndPullRequests({
      q: 'is:issue is:open label:bounty',
      per_page: 5,
      sort: 'updated',
      order: 'desc'
    });
    
    return data.items.map(item => ({
      number: item.number,
      title: item.title,
      bounty: threshold + Math.floor(Math.random() * 500), // Simulating bounty amounts for demo purposes
      repo: item.repository_url.replace('https://api.github.com/repos/', '')
    })).filter(issue => issue.bounty >= threshold);
  } catch (error) {
    console.error("Failed to scan bounties", error);
    return [];
  }
}

/**
 * tool: claimIssue
 * Leaves a comment stating the agent is working on the issue.
 */
export async function claimIssue(token: string, repo: string, issueNumber: number) {
  const octokit = new Octokit({ auth: token });
  const [owner, name] = repo.split('/');
  
  try {
    await octokit.rest.issues.createComment({
      owner,
      repo: name,
      issue_number: issueNumber,
      body: "🤖 Working on this automatically via Autonomous Bounty Hunter Agent... PR incoming."
    });
    console.log(`Claimed issue ${issueNumber} on ${repo}`);
  } catch(e) {
    console.warn(`Failed to claim issue ${issueNumber}`, e);
  }
}

/**
 * tool: writeFix
 * Generates the fix using Gemini LLM, returning structured JSON with file path and new content.
 */
export async function writeFix(title: string, repo: string): Promise<string> {
  const llm = new ChatGoogleGenerativeAI({
    model: "gemini-2.5-pro",
    temperature: 0,
    apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GEMINI_API_KEY
  });

  const prompt = PromptTemplate.fromTemplate(`
    You are an expert software engineer resolving a GitHub issue.
    Repository: {repo}
    Issue Title: {title}
    
    You must return a raw JSON object containing exactly two keys:
    "filePath": the relative path of the file to modify to resolve this issue.
    "content": the complete new content of the file.
    
    Please provide ONLY the raw JSON string. Do not use markdown \`\`\` wrappers.
  `);

  const chain = prompt.pipe(llm);
  const result = await chain.invoke({ repo, title });
  
  return result.text ? result.text.toString() : result.content.toString();
}

/**
 * tool: submitPR
 * Creates a branch, commits the fix, and opens a Pull Request.
 */
export async function submitPR(token: string, repo: string, issueNumber: number, fixRawJSON: string): Promise<string> {
  const octokit = new Octokit({ auth: token });
  const [owner, name] = repo.split('/');
  
  try {
    let fix;
    try {
      fix = JSON.parse(fixRawJSON.trim());
    } catch {
      // Basic fallback if LLM wraps in markdown
      fix = JSON.parse(fixRawJSON.replace(/```json/g, '').replace(/```/g, '').trim());
    }

    const { filePath, content } = fix;

    // 1. Get default branch
    const repoInfo = await octokit.rest.repos.get({ owner, repo: name });
    const defaultBranch = repoInfo.data.default_branch;

    // 2. Get latest commit SHA of default branch
    const refData = await octokit.rest.git.getRef({
      owner,
      repo: name,
      ref: `heads/${defaultBranch}`,
    });
    const latestCommitSha = refData.data.object.sha;

    // 3. Create a new branch
    const branchName = `fix/issue-${issueNumber}-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner,
      repo: name,
      ref: `refs/heads/${branchName}`,
      sha: latestCommitSha,
    });

    // 4. Get the target file's current SHA if it exists
    let currentFileSha;
    try {
      const fileData = await octokit.rest.repos.getContent({
        owner,
        repo: name,
        path: filePath,
        ref: branchName
      }) as any;
      currentFileSha = fileData.data.sha;
    } catch (e) {
      // File possibly doesn't exist yet
    }

    // 5. Update/Create the file
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo: name,
      path: filePath,
      message: `Fix issue #${issueNumber}`,
      content: Buffer.from(content).toString('base64'),
      branch: branchName,
      sha: currentFileSha
    });

    // 6. Create Pull Request
    const pr = await octokit.rest.pulls.create({
      owner,
      repo: name,
      title: `Fix: Resolve issue #${issueNumber}`,
      body: `Automated PR generated by Autonomous Agent to resolve #${issueNumber}.`,
      head: branchName,
      base: defaultBranch
    });

    return pr.data.html_url;
  } catch (error: any) {
    console.error("Failed to submit PR:", error.message);
    return `https://github.com/${repo}/issues/${issueNumber} (PR Failed)`;
  }
}
